#!/bin/sh

set -e # to exit as soon as there is an error

hollight_commit=4eef6f6
hol2dk_commit=b0293b4
lambdapi_commit=c24b28e2

opam_version=2.2.1
dune_version=3.17.0
ocaml_version=5.2.1
camlp5_version=8.03.01
coq_version=8.20.0

base=hol
dump_simp_option=-before-hol
root_path=HOLLight
jobs='-j32'

line() { echo '------------------------------------------------------------'; }

mkdir -p tmp
cd tmp

#usage: checkout_commit url commit
checkout_commit() {
    line
    d=`basename $1 .git`
    echo install $d ...
    git clone $1
    cd $d
    git checkout $2
    cd ..
}

create_opam_switch() {
    line
    echo create opam switch reproduce ...
    opam switch create reproduce $ocaml_version || (echo 'you can remove the opam switch reproduce with:'; echo 'opam switch remove reproduce'; exit 1)
}

install_hol_light_deps() {
    line
    echo install HOL-Light dependencies ...
    opam install -y camlp5.$camlp5_version ocamlfind zarith
}

install_lambdapi() {
    checkout_commit https://github.com/Deducteam/lambdapi.git $lambdapi_commit
    cd lambdapi
    git checkout -b reproduce
    opam install -y .
    cd ..
}

install_coq() {
    line
    echo install coq and package dependencies ...
    opam repo add coq-released https://coq.inria.fr/opam/released
    opam install -y coq.$coq_version
}

install_hol2dk() {
    checkout_commit https://github.com/Deducteam/hol2dk.git $hol2dk_commit
    cd hol2dk
    dune build && dune install
    cd ..
}

install_hol_light() {
    checkout_commit https://github.com/jrh13/hol-light.git $hollight_commit
    cd hol-light
    make
    cd ..
}

patch_hol_light() {
    line
    echo patch hol-light ...
    hol2dk patch
}

dump_proofs() {
    line
    echo dump hol-light proofs ...
    cd hol-light
    hol2dk dump-simp$dump_simp_option $base.ml
    cd ..
}

translate_proofs() {
    line
    echo translate HOL-Light proofs to lambdapi and coq ...
    mkdir -p output
    cd output
    hol2dk link $base.ml HOLLight_Real.HOLLight_Real --root-path ../../$root_path.v Rdefinitions Rbasic_fun Raxioms --erasing ../../erasing.lp
    make split
    make $jobs lp
    make $jobs v
    cd ..
}

check_proofs() {
    line
    echo check proofs ...
    cd output
    make $jobs vo
    make opam
    cd ..
}

create_and_check_opam_library() {
    line
    echo create opam library ...
    mkdir -p opam
    cd output
    cp theory_hol.v ../opam
    sed -e "s/${base}_//g" -e "/^Require Import ${root_path}.types.$/d" ${base}_terms.v > ../opam/terms.v
    sed -e "s/${base}_//g" -e "/^Require Import ${root_path}.types.$/d" -e '/^Require Import ${root_path}.axioms.$/d' ${base}_opam.v > ../opam/theorems.v
    cd ../opam
    cp ../../$root_path.v ../../Makefile .
    make
    cd ..
}

export HOLLIGHT_DIR=`pwd`/hol-light
export HOL2DK_DIR=`pwd`/hol2dk

setup_env() {
    create_opam_switch
    install_hol_light_deps
    install_lambdapi
    install_coq
    install_hol2dk
    install_hol_light
    patch_hol_light
}

setup_env
dump_proofs
translate_proofs
check_proofs
create_and_check_opam_library

line
echo remove opam switch reproduce ...
opam switch remove reproduce
