#!/bin/sh

set -e # to exit as soon as there is an error

hollight_version=3.0.0 # for dependencies
hollight_commit=28e4aed
hol2dk_commit=5390465
lambdapi_commit=eeb280b9
coq_hollight_real_commit=ccbeb9d
ocaml_version=5.3.0
rocq_version=9.0.0

opam_version=2.3.0
dune_version=3.19.1
camlp5_version=8.03.05

hollight_file=Multivariate/make_complex.ml
base=`basename $hollight_file .ml`
root_path=HOLLight
: "${NB_CORES:=$(nproc)}"
jobs="-j$NB_CORES"

one_stage="false"

usage() {
    echo "usage: `NB_CORES= [NBRE_OF_AVAILABLE_CORES] basename $0` [STAGE_NUMBER]"
    echo
    echo 'do stages from STAGE_NUMBER or last failing stage using NBRE_OF_AVAILABLE_CORES jobs'
    echo
    echo 'options:'
    echo '  -h|--help: print help'
    echo '  -o|--only: do the provided stage only without following ones'
    echo '  -y: do not ask for user input, proceed automatically'
    echo
    echo 'stages:'
    grep '^stage ' $0 | sed -e 's/^stage/ /'
}

parse_args() {
    if test $# -gt 0
    then
        case $1 in
            -h|--help) usage; exit 0;;
            -y) do_not_ask=1; shift; parse_args $*;;
            -o|--only) one_stage="true";shift; parse_args $*;;
            *)
                if test $1 -le 0 -o $1 -gt 15
                then
                    echo 'error: invalid stage number'
                    usage
                    exit 1
                else
                    if test $# -gt 1
                    then
                        echo 'error: too many arguments'
                        usage
                        exit 1
                    fi
                fi;;
        esac
    fi
}

parse_args $*

# usage: ask text
ask() {
    if test "$do_not_ask" != 1
    then
        read -p "$1 (y/n)? " answer
        echo $answer
    else
        echo y
    fi
}

mkdir -p tmp
cd tmp

#usage: checkout_commit url commit
checkout_commit() {
    d=`basename $1 .git`
    if test ! -d "$d"
    then
        echo git clone $1 ...
        git clone $1
        cd $d
        echo git checkout $2 ...
        git checkout $2
        cd ..
    fi
}

#usage: install_commit url commit
install_commit() {
    checkout_commit $*
    # if test `git branch | grep reproduce | wc -l` -gt 0
    # then
    d=`basename $1 .git`
    cd $d
    git checkout -b reproduce
    echo opam install $d ...
    opam install -y .
    cd ..
    echo $d installed successfully
    # fi
}

create_opam_switch() {
    s=`opam switch show`
    c=`pwd`
    if test "$s" != "$c"
    then
        echo opam switch create $c ...
        opam switch create . $ocaml_version
    fi
}

install_hollight_deps() {
    echo install HOL-Light dependencies ...
    opam install -y --deps-only hol_light.$hollight_version
}

install_lambdapi() {
    # newer versions of cmdliner break old versions of LP
    opam install -y cmdliner.1.3.0
    install_commit https://github.com/Deducteam/lambdapi.git $lambdapi_commit
}

install_rocq() {
    echo install rocq ...
    opam install -y rocq-prover.$rocq_version
}

install_deps() {
    echo install coq-hol-light dependencies ...
    opam repo add rocq-released https://rocq-prover.org/opam/released
    opam install -y --deps-only ..
}

install_coq_hollight_real() {
    install_commit https://github.com/Deducteam/coq-hol-light-real-with-N $coq_hollight_real_commit
}

install_hol2dk() {
    checkout_commit https://github.com/Deducteam/hol2dk.git $hol2dk_commit
    cd hol2dk
    echo install hol2dk ...
    dune build && dune install
    cd ..
}

install_hollight() {
    checkout_commit https://github.com/jrh13/hol-light.git $hollight_commit
    cd hol-light
    echo configure hol-light ...
    make
    cd ..
}

patch_hollight() {
    if test ! -f hol-light/fusion-bak.ml
    then
        echo patch hol-light ...
        hol2dk patch
    fi
}

dump_proofs() {
    if test -f hol-light/$hollight_file
    then
        echo dump hol-light proofs ...
        cd hol-light
        hol2dk dump-simp $hollight_file
        cd ..
    else
        echo can\'t find $(pwd)/hol-light/$hollight_file. Please make sure to run stages 1 to 5
        echo and re-run the script from the repository root folder.
    fi
}

config_output_dir() {
    if test ! -d output
    then
        echo configure output directory ...
        mkdir -p output
        cd output
        if test -f Makefile; then make $jobs clean-all; fi
        hol2dk config $hollight_file $root_path Stdlib.NArith.BinNat Stdlib.Reals.Reals HOLLight_Real_With_N.mappings ../../mappings.v ../../mappings.lp
        cd ..
    fi
}
    
translate_proofs() {
    if test "`ask 'translate proofs'`" = 'y'
    then
        echo translate HOL-Light proofs to lambdapi and rocq ...
        cd output
        echo "time to split files:" >&2
        /bin/bash -c time make split
        echo "time to generate .lp files:" >&2
        /bin/bash -c time make $jobs lp
        echo "time to generate .v files:" >&2
        /bin/bash -c time make $jobs v
        echo "time to merge spec files:" >&2
        /bin/bash -c time make $jobs merge-spec-files
        echo "time to remove empty deps:" >&2
        /bin/bash -c time make $jobs rm-empty-deps
        cd ..
    fi
}

check_proofs() {
    if test "`ask 'check proofs'`" = 'y'
    then
        echo check proofs ...
        cd output
        echo "time to check .v files:" >&2
        /bin/bash -c time make $jobs -k vo
        cd ..
    fi
}

remove_empty_modules() {
    sed -e "s/${base}_//g" \
        -e "/^Require Import ${root_path}\.theory_hol\.$/d" \
        -e "/^Require Import ${root_path}\.types\.$/d" \
        -e "/^Require Import ${root_path}\.axioms\.$/d" \
        -e 's/NUMERAL //g' \
        $1
}

create_and_check_opam_library() {
    echo create opam library ...
    cd output
    make $jobs opam
    cd ..
    mkdir -p opam
    cd opam
    cp ../../Makefile ../../mappings.v .
    remove_empty_modules ../output/${base}_terms.v > terms.v
    remove_empty_modules ../output/${base}_opam.v > theorems.v
    sed -i -e 's/NUMERAL //g' -e 's/(N0)/N0/g' terms.v theorems.v
    make $jobs
    cd ..
}

compare_opam_file() {
    echo compare $1 ...
    diff ../$1 opam/$1
}

compare_opam_files() {
    for f in terms.v theorems.v
    do
        compare_opam_file $f
    done
}

export HOLLIGHT_DIR=`pwd`/hol-light
export HOL2DK_DIR=`pwd`/hol2dk

stage() {
    if test -f STAGE
    then
        i=`head -n1 STAGE`
        i=`expr $i + 1`
    else
        i=1
    fi
    if test $i -eq $1
    then
        echo '------------------------------------------------------------'
        echo stage $*
        $2
        touch stage_$1_$2.ok
        if test $one_stage = "true"
        then
            echo 20 > STAGE
        else
            echo $1 > STAGE
        fi
    fi
}

while test -n "$2"
do
    shift
done

if test -n "$1"
then
    echo `expr $1 - 1` > STAGE
fi

stage 1 create_opam_switch
eval `opam env`
stage 2 install_hollight_deps
stage 3 install_lambdapi
stage 4 install_rocq
stage 5 install_deps
stage 6 install_coq_hollight_real
stage 7 install_hol2dk
stage 8 install_hollight
stage 9 patch_hollight
stage 10 dump_proofs
stage 11 config_output_dir
stage 12 create_and_check_opam_library
stage 13 compare_opam_files
stage 14 translate_proofs
stage 15 check_proofs
